### ISSUE TITLE
GPL without additional permission is imcompatible with Oracle library.

### ISSUE THREAD

**Issue by kubo** [digitalfox/pysql#3]
Look at http://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs
Could you change the license term to add permission to link with Oracle library?

**Comment by digitalfox** [comment]
Hello,

Thanks for pointing out this issue. However, pysql is not directly linked to Oracle libraries but to cx_Oracle library (which is itself effectively linked to Oracle). Cx_Oracle has a free software licence (which is not GPL) :  
http://cx-oracle.sourceforge.net/LICENSE.txt

So, I don't known if we really need that exception in this case. 

Regards

**Comment by kubo** [comment]
In http://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation

> If modules are designed to run linked together in a shared address space, that almost surely means combining them into one program.

pysql, Cx_Oracle and Oracle libraries are combined because they are linked together in a shared address space.

In http://www.gnu.org/licenses/gpl-faq.en.html#GPLModuleLicense

> The GPL says that the whole combined program has to be released under the GPL. So your module has to be available for use under the GPL.

pysql is released under the GPL. Therefore Cx_Oracle and Oracle libraries have to be available for use under the GPL.
Cx_Oracle's license is compatible with the GPL, but Oracle libraries are not.

**Comment by digitalfox** [comment]
Thanks for this precise comment. I updated the license file to reflect your comment (see b085ce2fd937a1d2a015d8a639bb16ce79611bf6). Hopes this is now correct.

**Comment by kubo** [comment]
Could you change "cx_Oracle and Oracle driver" to "Oracle Database Client"?
The cx_Oracle license is the modified BSD license. It is listed in [GPL-Compatible Free Software Licenses](http://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses). You have no need to grant additional permission to cx_Oracle.
It is not clear what Oracle driver means. It should be an official name. What I refer to as Oracle libraries is documented as "Oracle Database Client" in [Oracle manuals](http://docs.oracle.com/cd/E11882_01/install.112/e24322/install_overview.htm#BABFAEJE)

**Comment by kubo** [comment]
In addition to the LICENSE file, could you change the license notice in http://pysql.sourceforge.net/.

**Comment by digitalfox** [comment]
Ok, I remove mention to cx_Oracle. But use "database Oracle driver", instead of "client" not to confuse with oracle client (sql*plus) which is not involve at all.
See commit ae8fdc3cf4d0c

Website was updated as well to link to LICENCE file.

**Comment by kubo** [comment]
Thank you!
